package com.foodie.pojo;

public class Choice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.itemid
     *
     * @mbg.generated
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.stuid
     *
     * @mbg.generated
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.examid
     *
     * @mbg.generated
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.stuanswer
     *
     * @mbg.generated
     */
    private String stuanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.iscorrect
     *
     * @mbg.generated
     */
    private Boolean iscorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.stupoint
     *
     * @mbg.generated
     */
    private String stupoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.itemid
     *
     * @return the value of choice.itemid
     *
     * @mbg.generated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.itemid
     *
     * @param itemid the value for choice.itemid
     *
     * @mbg.generated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.stuid
     *
     * @return the value of choice.stuid
     *
     * @mbg.generated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.stuid
     *
     * @param stuid the value for choice.stuid
     *
     * @mbg.generated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.examid
     *
     * @return the value of choice.examid
     *
     * @mbg.generated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.examid
     *
     * @param examid the value for choice.examid
     *
     * @mbg.generated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.stuanswer
     *
     * @return the value of choice.stuanswer
     *
     * @mbg.generated
     */
    public String getStuanswer() {
        return stuanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.stuanswer
     *
     * @param stuanswer the value for choice.stuanswer
     *
     * @mbg.generated
     */
    public void setStuanswer(String stuanswer) {
        this.stuanswer = stuanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.iscorrect
     *
     * @return the value of choice.iscorrect
     *
     * @mbg.generated
     */
    public Boolean getIscorrect() {
        return iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.iscorrect
     *
     * @param iscorrect the value for choice.iscorrect
     *
     * @mbg.generated
     */
    public void setIscorrect(Boolean iscorrect) {
        this.iscorrect = iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.stupoint
     *
     * @return the value of choice.stupoint
     *
     * @mbg.generated
     */
    public String getStupoint() {
        return stupoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.stupoint
     *
     * @param stupoint the value for choice.stupoint
     *
     * @mbg.generated
     */
    public void setStupoint(String stupoint) {
        this.stupoint = stupoint;
    }
}