package com.foodie.pojo;

import java.util.Date;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.examid
     *
     * @mbg.generated
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.teaid
     *
     * @mbg.generated
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.publishstate
     *
     * @mbg.generated
     */
    private Boolean publishstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.examid
     *
     * @return the value of exam.examid
     *
     * @mbg.generated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.examid
     *
     * @param examid the value for exam.examid
     *
     * @mbg.generated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.teaid
     *
     * @return the value of exam.teaid
     *
     * @mbg.generated
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.teaid
     *
     * @param teaid the value for exam.teaid
     *
     * @mbg.generated
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.createtime
     *
     * @return the value of exam.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.createtime
     *
     * @param createtime the value for exam.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.title
     *
     * @return the value of exam.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.title
     *
     * @param title the value for exam.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.duration
     *
     * @return the value of exam.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.duration
     *
     * @param duration the value for exam.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.publishstate
     *
     * @return the value of exam.publishstate
     *
     * @mbg.generated
     */
    public Boolean getPublishstate() {
        return publishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.publishstate
     *
     * @param publishstate the value for exam.publishstate
     *
     * @mbg.generated
     */
    public void setPublishstate(Boolean publishstate) {
        this.publishstate = publishstate;
    }
}