package com.foodie.pojo;


public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemid
     *
     * @mbg.generated
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.examid
     *
     * @mbg.generated
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.a
     *
     * @mbg.generated
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.b
     *
     * @mbg.generated
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.c
     *
     * @mbg.generated
     */
    private String c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.d
     *
     * @mbg.generated
     */
    private String d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.rightanswer
     *
     * @mbg.generated
     */
    private String rightanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.point
     *
     * @mbg.generated
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemid
     *
     * @return the value of item.itemid
     *
     * @mbg.generated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemid
     *
     * @param itemid the value for item.itemid
     *
     * @mbg.generated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.examid
     *
     * @return the value of item.examid
     *
     * @mbg.generated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.examid
     *
     * @param examid the value for item.examid
     *
     * @mbg.generated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.type
     *
     * @return the value of item.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.type
     *
     * @param type the value for item.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.content
     *
     * @return the value of item.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.content
     *
     * @param content the value for item.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.a
     *
     * @return the value of item.a
     *
     * @mbg.generated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.a
     *
     * @param a the value for item.a
     *
     * @mbg.generated
     */
    public void setA(String a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.b
     *
     * @return the value of item.b
     *
     * @mbg.generated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.b
     *
     * @param b the value for item.b
     *
     * @mbg.generated
     */
    public void setB(String b) {
        this.b = b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.c
     *
     * @return the value of item.c
     *
     * @mbg.generated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.c
     *
     * @param c the value for item.c
     *
     * @mbg.generated
     */
    public void setC(String c) {
        this.c = c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.d
     *
     * @return the value of item.d
     *
     * @mbg.generated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.d
     *
     * @param d the value for item.d
     *
     * @mbg.generated
     */
    public void setD(String d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.rightanswer
     *
     * @return the value of item.rightanswer
     *
     * @mbg.generated
     */
    public String getRightanswer() {
        return rightanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.rightanswer
     *
     * @param rightanswer the value for item.rightanswer
     *
     * @mbg.generated
     */
    public void setRightanswer(String rightanswer) {
        this.rightanswer = rightanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.point
     *
     * @return the value of item.point
     *
     * @mbg.generated
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.point
     *
     * @param point the value for item.point
     *
     * @mbg.generated
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}