package com.foodie.pojo;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuid
     *
     * @mbg.generated
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated
     */
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.academy
     *
     * @mbg.generated
     */
    private String academy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.startyear
     *
     * @mbg.generated
     */
    private Date startyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.degree
     *
     * @mbg.generated
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.batchid
     *
     * @mbg.generated
     */
    private Integer batchid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuid
     *
     * @return the value of student.stuid
     *
     * @mbg.generated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuid
     *
     * @param stuid the value for student.stuid
     *
     * @mbg.generated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.academy
     *
     * @return the value of student.academy
     *
     * @mbg.generated
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.academy
     *
     * @param academy the value for student.academy
     *
     * @mbg.generated
     */
    public void setAcademy(String academy) {
        this.academy = academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.startyear
     *
     * @return the value of student.startyear
     *
     * @mbg.generated
     */
    public Date getStartyear() {
        return startyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.startyear
     *
     * @param startyear the value for student.startyear
     *
     * @mbg.generated
     */
    public void setStartyear(Date startyear) {
        this.startyear = startyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.degree
     *
     * @return the value of student.degree
     *
     * @mbg.generated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.degree
     *
     * @param degree the value for student.degree
     *
     * @mbg.generated
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.batchid
     *
     * @return the value of student.batchid
     *
     * @mbg.generated
     */
    public Integer getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.batchid
     *
     * @param batchid the value for student.batchid
     *
     * @mbg.generated
     */
    public void setBatchid(Integer batchid) {
        this.batchid = batchid;
    }
}