package com.foodie.pojo;

import java.io.Serializable;

public class Teacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaid
     *
     * @mbg.generated
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated
     */
    private String name;

    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaid
     *
     * @return the value of teacher.teaid
     *
     * @mbg.generated
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaid
     *
     * @param teaid the value for teacher.teaid
     *
     * @mbg.generated
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}