package com.foodie.pojo;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.stuid
     *
     * @mbg.generated
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.examid
     *
     * @mbg.generated
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.submitstate
     *
     * @mbg.generated
     */
    private Boolean submitstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.totalmark
     *
     * @mbg.generated
     */
    private Integer totalmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.stuid
     *
     * @return the value of test.stuid
     *
     * @mbg.generated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.stuid
     *
     * @param stuid the value for test.stuid
     *
     * @mbg.generated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.examid
     *
     * @return the value of test.examid
     *
     * @mbg.generated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.examid
     *
     * @param examid the value for test.examid
     *
     * @mbg.generated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.submitstate
     *
     * @return the value of test.submitstate
     *
     * @mbg.generated
     */
    public Boolean getSubmitstate() {
        return submitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.submitstate
     *
     * @param submitstate the value for test.submitstate
     *
     * @mbg.generated
     */
    public void setSubmitstate(Boolean submitstate) {
        this.submitstate = submitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.totalmark
     *
     * @return the value of test.totalmark
     *
     * @mbg.generated
     */
    public Integer getTotalmark() {
        return totalmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.totalmark
     *
     * @param totalmark the value for test.totalmark
     *
     * @mbg.generated
     */
    public void setTotalmark(Integer totalmark) {
        this.totalmark = totalmark;
    }
}