server:
  port: 6003
spring:
  application:
    name: demoserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.252.131:3306/hmq #最新的数据库，可连接。
    username: root
    password: 0qYggB%jjQf_
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
#  rabbitmq:
#    host: www.foodiesquad.top
#    username: foodie
#    password: foodie123
eureka:
  client:
    serviceUrl:
      defaultZone: http://euk1.com:7001/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true


mybatis:
  mapper-locations: classpath:com/foodie/mapper/*.xml



  #包含的服务，也可以exclude,服务中心就不上线
  #management.endpoints.web.exposure.include=*

  #可以远程关闭服务节点
  #management.endpoint.shutdown.enabled=true

  #可以上报服务的真实健康状态
  #eureka.client.health
