package com.foodie.itemprovider.mapper;

import com.foodie.pojo.Publish;
import java.util.List;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated
     */
    List<Publish> selectAll();
}