package com.foodie.examprovider.mapper;

import com.foodie.pojo.Choice;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface ChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    int insert(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    List<Choice> selectAll();

    int update(Choice record);

    Choice selectByStuIdAndExamIdAndItemId(@Param("stuid") Integer stuid, @Param("examid") Integer examid, @Param("itemid")Integer itemid);
}