package com.foodie.examprovider.mapper;

import com.foodie.dto.StuGetReq;
import com.foodie.pojo.Test;
import java.util.List;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    List<Test> selectAll();

    Test selectByStuIdAndExamId(StuGetReq stuGetReq);

    int update(Test record);
}